/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("NotificationsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheNotificationsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheNotificationsList.onFilterBar().iCheckFilterField("MaintenanceNotification");
            Then.onTheNotificationsList.onFilterBar().iCheckFilterField("NotificationType");
            Then.onTheNotificationsList.onFilterBar().iCheckFilterField("MaintPriority");
            Then.onTheNotificationsList.onFilterBar().iCheckFilterField("NotifProcessingPhase");
            Then.onTheNotificationsList.onFilterBar().iCheckFilterField("MaintenancePlant");
            Then.onTheNotificationsList.onFilterBar().iCheckFilterField("CreatedByUser");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheNotificationsList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheNotificationsList.onFilterBar().iExecuteSearch();
        //     Then.onTheNotificationsList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheNotificationsList.onTable().iCheckColumns(undefined, {"MaintenanceNotification":{"header":"Notification"},"NotificationText":{"header":"Description"},"NotificationType":{"header":"Type"},"MaintPriority":{"header":"Priority"},"NotifProcessingPhaseDesc":{"header":"Status"},"TechnicalObjectLabel":{"header":"Technical Object"},"MaintenancePlantName":{"header":"Plant"},"MainWorkCenterText":{"header":"Work Center"},"CreationDate":{"header":"Created On"},"CreatedByUser":{"header":"Created By"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheNotificationsList.onFilterBar().iExecuteSearch();
            
            Then.onTheNotificationsList.onTable().iCheckRows();

            When.onTheNotificationsList.onTable().iPressRow(0);
            Then.onTheNotificationsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});