/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("NotificationsObjectPageObjectPage journey");

        opaTest("Navigate to NotificationsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheNotificationsList.onFilterBar().iExecuteSearch();

            Then.onTheNotificationsList.onTable().iCheckRows();
            When.onTheNotificationsList.onTable().iPressRow(0);

            Then.onTheNotificationsObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheNotificationsObjectPage.iCheckNumberOfSections(5);
            When.onTheNotificationsObjectPage.iPressSectionIconTabFilterButton("GeneralInfo");
            Then.onTheNotificationsObjectPage.iCheckSection({ section: "GeneralInfo" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MaintenanceNotification" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "NotificationText" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "NotificationType" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MaintPriority" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MaintPriorityDesc" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "NotifProcessingPhaseDesc" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MaintNotifLongTextForEdit" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CompanyCode" });
            Then.onTheNotificationsObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedByUser" });
            When.onTheNotificationsObjectPage.iPressSectionIconTabFilterButton("TechnicalObject");
            Then.onTheNotificationsObjectPage.iCheckSection({ section: "TechnicalObject" });
            Then.onTheNotificationsObjectPage.onForm({ section: "TechnicalObject" }).iCheckField({ property: "TechnicalObjectLabel" });
            Then.onTheNotificationsObjectPage.onForm({ section: "TechnicalObject" }).iCheckField({ property: "TechnicalObjectDescription" });
            Then.onTheNotificationsObjectPage.onForm({ section: "TechnicalObject" }).iCheckField({ property: "TechObjIsEquipOrFuncnlLoc" });
            Then.onTheNotificationsObjectPage.onForm({ section: "TechnicalObject" }).iCheckField({ property: "FunctionalLocationLabelName" });
            Then.onTheNotificationsObjectPage.onForm({ section: "TechnicalObject" }).iCheckField({ property: "MaintenanceObjectIsDown" });
            When.onTheNotificationsObjectPage.iPressSectionIconTabFilterButton("Dates");
            Then.onTheNotificationsObjectPage.iCheckSection({ section: "Dates" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Dates" }).iCheckField({ property: "CreationDate" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Dates" }).iCheckField({ property: "RequiredStartDate" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Dates" }).iCheckField({ property: "RequiredEndDate" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Dates" }).iCheckField({ property: "LatestAcceptableCompletionDate" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Dates" }).iCheckField({ property: "NotificationCompletionDate" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Dates" }).iCheckField({ property: "LastChangeDateTime" });
            When.onTheNotificationsObjectPage.iPressSectionIconTabFilterButton("Maintenance");
            Then.onTheNotificationsObjectPage.iCheckSection({ section: "Maintenance" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Maintenance" }).iCheckField({ property: "MaintenancePlantName" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Maintenance" }).iCheckField({ property: "MaintenancePlannerGroupName" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Maintenance" }).iCheckField({ property: "MainWorkCenterText" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Maintenance" }).iCheckField({ property: "MaintenanceOrder" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Maintenance" }).iCheckField({ property: "MaintenanceOrderType" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Maintenance" }).iCheckField({ property: "MaintenanceActivityType" });
            Then.onTheNotificationsObjectPage.onForm({ section: "Maintenance" }).iCheckField({ property: "ConcatenatedActiveSystStsName" });
            When.onTheNotificationsObjectPage.iPressSectionIconTabFilterButton("ItemsFacet");
            Then.onTheNotificationsObjectPage.iCheckSection({ section: "ItemsFacet" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});